Modify Jenkinsfile to define path to requirements.txt

diff --git a/messaging_app/messaging_app/Jenkinsfile b/messaging_app/messaging_app/Jenkinsfile
--- a/messaging_app/messaging_app/Jenkinsfile
+++ b/messaging_app/messaging_app/Jenkinsfile
@@ -140,21 +140,22 @@ pipeline {
                 }
             }
         }
+        
+        stage('Cleanup Docker Images') {
+            steps {
+                echo 'Cleaning up local Docker images...'
+                sh '''
+                    # Clean up Docker images to save space
+                    docker rmi -f $(docker images -q ${DOCKER_REPO}/${DOCKER_IMAGE}) || true
+                    docker system prune -f || true
+                '''
+            }
+        }
     }
     
     post {
         always {
             echo 'Pipeline completed!'
-            // Clean up Docker images to save space - wrap in node context
-            script {
-                try {
-                    sh '''
-                        docker rmi -f $(docker images -q ${DOCKER_REPO}/${DOCKER_IMAGE}) || true
-                    '''
-                } catch (Exception e) {
-                    echo "Failed to clean up Docker images: ${e.getMessage()}"
-                }
-            }
             cleanWs()
         }
         success {
